// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"time"
)

const (
	ForwardedUserScopes forwardedUserContextKey = "forwardedUser.Scopes"
)

// Defines values for CardCellState.
const (
	Bingo  CardCellState = "bingo"
	Closed CardCellState = "closed"
	Open   CardCellState = "open"
	Reach  CardCellState = "reach"
)

// Valid indicates whether the value is a known member of the CardCellState enum.
func (e CardCellState) Valid() bool {
	switch e {
	case Bingo:
		return true
	case Closed:
		return true
	case Open:
		return true
	case Reach:
		return true
	default:
		return false
	}
}

// Defines values for DisplayAllPickedEventType.
const (
	DisplayAllPickedEventTypeAllPicked DisplayAllPickedEventType = "AllPicked"
)

// Valid indicates whether the value is a known member of the DisplayAllPickedEventType enum.
func (e DisplayAllPickedEventType) Valid() bool {
	switch e {
	case DisplayAllPickedEventTypeAllPicked:
		return true
	default:
		return false
	}
}

// Defines values for DisplayGameFinishedBodyPickState.
const (
	DisplayGameFinishedBodyPickStateIdle DisplayGameFinishedBodyPickState = "idle"
)

// Valid indicates whether the value is a known member of the DisplayGameFinishedBodyPickState enum.
func (e DisplayGameFinishedBodyPickState) Valid() bool {
	switch e {
	case DisplayGameFinishedBodyPickStateIdle:
		return true
	default:
		return false
	}
}

// Defines values for DisplayGameFinishedBodyState.
const (
	DisplayGameFinishedBodyStateFinished DisplayGameFinishedBodyState = "finished"
)

// Valid indicates whether the value is a known member of the DisplayGameFinishedBodyState enum.
func (e DisplayGameFinishedBodyState) Valid() bool {
	switch e {
	case DisplayGameFinishedBodyStateFinished:
		return true
	default:
		return false
	}
}

// Defines values for DisplayGameFinishedEventType.
const (
	DisplayGameFinishedEventTypeGameFinished DisplayGameFinishedEventType = "GameFinished"
)

// Valid indicates whether the value is a known member of the DisplayGameFinishedEventType enum.
func (e DisplayGameFinishedEventType) Valid() bool {
	switch e {
	case DisplayGameFinishedEventTypeGameFinished:
		return true
	default:
		return false
	}
}

// Defines values for DisplayGameSettingsUpdatedEventType.
const (
	DisplayGameSettingsUpdatedEventTypeGameSettingsUpdated DisplayGameSettingsUpdatedEventType = "GameSettingsUpdated"
)

// Valid indicates whether the value is a known member of the DisplayGameSettingsUpdatedEventType enum.
func (e DisplayGameSettingsUpdatedEventType) Valid() bool {
	switch e {
	case DisplayGameSettingsUpdatedEventTypeGameSettingsUpdated:
		return true
	default:
		return false
	}
}

// Defines values for DisplayGameStartedEventType.
const (
	DisplayGameStartedEventTypeGameStarted DisplayGameStartedEventType = "GameStarted"
)

// Valid indicates whether the value is a known member of the DisplayGameStartedEventType enum.
func (e DisplayGameStartedEventType) Valid() bool {
	switch e {
	case DisplayGameStartedEventTypeGameStarted:
		return true
	default:
		return false
	}
}

// Defines values for DisplayHideQRCodeEventType.
const (
	DisplayHideQRCodeEventTypeHideQRCode DisplayHideQRCodeEventType = "HideQRCode"
)

// Valid indicates whether the value is a known member of the DisplayHideQRCodeEventType enum.
func (e DisplayHideQRCodeEventType) Valid() bool {
	switch e {
	case DisplayHideQRCodeEventTypeHideQRCode:
		return true
	default:
		return false
	}
}

// Defines values for DisplayInitializedEventType.
const (
	DisplayInitializedEventTypeInitialized DisplayInitializedEventType = "Initialized"
)

// Valid indicates whether the value is a known member of the DisplayInitializedEventType enum.
func (e DisplayInitializedEventType) Valid() bool {
	switch e {
	case DisplayInitializedEventTypeInitialized:
		return true
	default:
		return false
	}
}

// Defines values for DisplayMessageCreatedEventType.
const (
	DisplayMessageCreatedEventTypeMessageCreated DisplayMessageCreatedEventType = "MessageCreated"
)

// Valid indicates whether the value is a known member of the DisplayMessageCreatedEventType enum.
func (e DisplayMessageCreatedEventType) Valid() bool {
	switch e {
	case DisplayMessageCreatedEventTypeMessageCreated:
		return true
	default:
		return false
	}
}

// Defines values for DisplayPickCanceledEventType.
const (
	DisplayPickCanceledEventTypePickCanceled DisplayPickCanceledEventType = "PickCanceled"
)

// Valid indicates whether the value is a known member of the DisplayPickCanceledEventType enum.
func (e DisplayPickCanceledEventType) Valid() bool {
	switch e {
	case DisplayPickCanceledEventTypePickCanceled:
		return true
	default:
		return false
	}
}

// Defines values for DisplayPickFinishedEventType.
const (
	DisplayPickFinishedEventTypePickFinished DisplayPickFinishedEventType = "PickFinished"
)

// Valid indicates whether the value is a known member of the DisplayPickFinishedEventType enum.
func (e DisplayPickFinishedEventType) Valid() bool {
	switch e {
	case DisplayPickFinishedEventTypePickFinished:
		return true
	default:
		return false
	}
}

// Defines values for DisplayPickStartedEventType.
const (
	DisplayPickStartedEventTypePickStarted DisplayPickStartedEventType = "PickStarted"
)

// Valid indicates whether the value is a known member of the DisplayPickStartedEventType enum.
func (e DisplayPickStartedEventType) Valid() bool {
	switch e {
	case DisplayPickStartedEventTypePickStarted:
		return true
	default:
		return false
	}
}

// Defines values for DisplayShowQRCodeEventType.
const (
	ShowQRCode DisplayShowQRCodeEventType = "ShowQRCode"
)

// Valid indicates whether the value is a known member of the DisplayShowQRCodeEventType enum.
func (e DisplayShowQRCodeEventType) Valid() bool {
	switch e {
	case ShowQRCode:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantAllPickedEventType.
const (
	ParticipantAllPickedEventTypeAllPicked ParticipantAllPickedEventType = "AllPicked"
)

// Valid indicates whether the value is a known member of the ParticipantAllPickedEventType enum.
func (e ParticipantAllPickedEventType) Valid() bool {
	switch e {
	case ParticipantAllPickedEventTypeAllPicked:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantGameFinishedBodyPickState.
const (
	ParticipantGameFinishedBodyPickStateIdle ParticipantGameFinishedBodyPickState = "idle"
)

// Valid indicates whether the value is a known member of the ParticipantGameFinishedBodyPickState enum.
func (e ParticipantGameFinishedBodyPickState) Valid() bool {
	switch e {
	case ParticipantGameFinishedBodyPickStateIdle:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantGameFinishedBodyState.
const (
	ParticipantGameFinishedBodyStateFinished ParticipantGameFinishedBodyState = "finished"
)

// Valid indicates whether the value is a known member of the ParticipantGameFinishedBodyState enum.
func (e ParticipantGameFinishedBodyState) Valid() bool {
	switch e {
	case ParticipantGameFinishedBodyStateFinished:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantGameFinishedEventType.
const (
	ParticipantGameFinishedEventTypeGameFinished ParticipantGameFinishedEventType = "GameFinished"
)

// Valid indicates whether the value is a known member of the ParticipantGameFinishedEventType enum.
func (e ParticipantGameFinishedEventType) Valid() bool {
	switch e {
	case ParticipantGameFinishedEventTypeGameFinished:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantGameSettingsUpdatedEventType.
const (
	ParticipantGameSettingsUpdatedEventTypeGameSettingsUpdated ParticipantGameSettingsUpdatedEventType = "GameSettingsUpdated"
)

// Valid indicates whether the value is a known member of the ParticipantGameSettingsUpdatedEventType enum.
func (e ParticipantGameSettingsUpdatedEventType) Valid() bool {
	switch e {
	case ParticipantGameSettingsUpdatedEventTypeGameSettingsUpdated:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantGameStartedEventType.
const (
	ParticipantGameStartedEventTypeGameStarted ParticipantGameStartedEventType = "GameStarted"
)

// Valid indicates whether the value is a known member of the ParticipantGameStartedEventType enum.
func (e ParticipantGameStartedEventType) Valid() bool {
	switch e {
	case ParticipantGameStartedEventTypeGameStarted:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantInitializedEventType.
const (
	ParticipantInitializedEventTypeInitialized ParticipantInitializedEventType = "Initialized"
)

// Valid indicates whether the value is a known member of the ParticipantInitializedEventType enum.
func (e ParticipantInitializedEventType) Valid() bool {
	switch e {
	case ParticipantInitializedEventTypeInitialized:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantMessageCreatedEventType.
const (
	ParticipantMessageCreatedEventTypeMessageCreated ParticipantMessageCreatedEventType = "MessageCreated"
)

// Valid indicates whether the value is a known member of the ParticipantMessageCreatedEventType enum.
func (e ParticipantMessageCreatedEventType) Valid() bool {
	switch e {
	case ParticipantMessageCreatedEventTypeMessageCreated:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantPickCanceledEventType.
const (
	ParticipantPickCanceledEventTypePickCanceled ParticipantPickCanceledEventType = "PickCanceled"
)

// Valid indicates whether the value is a known member of the ParticipantPickCanceledEventType enum.
func (e ParticipantPickCanceledEventType) Valid() bool {
	switch e {
	case ParticipantPickCanceledEventTypePickCanceled:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantPickFinishedEventType.
const (
	ParticipantPickFinishedEventTypePickFinished ParticipantPickFinishedEventType = "PickFinished"
)

// Valid indicates whether the value is a known member of the ParticipantPickFinishedEventType enum.
func (e ParticipantPickFinishedEventType) Valid() bool {
	switch e {
	case ParticipantPickFinishedEventTypePickFinished:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantPickStartedEventType.
const (
	ParticipantPickStartedEventTypePickStarted ParticipantPickStartedEventType = "PickStarted"
)

// Valid indicates whether the value is a known member of the ParticipantPickStartedEventType enum.
func (e ParticipantPickStartedEventType) Valid() bool {
	switch e {
	case ParticipantPickStartedEventTypePickStarted:
		return true
	default:
		return false
	}
}

// Defines values for PickState.
const (
	Exhausted PickState = "exhausted"
	Idle      PickState = "idle"
	Picking   PickState = "picking"
)

// Valid indicates whether the value is a known member of the PickState enum.
func (e PickState) Valid() bool {
	switch e {
	case Exhausted:
		return true
	case Idle:
		return true
	case Picking:
		return true
	default:
		return false
	}
}

// Defines values for RoomState.
const (
	Finished RoomState = "finished"
	Playing  RoomState = "playing"
	Waiting  RoomState = "waiting"
)

// Valid indicates whether the value is a known member of the RoomState enum.
func (e RoomState) Valid() bool {
	switch e {
	case Finished:
		return true
	case Playing:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for WebSocketEventType.
const (
	WebSocketEventTypeAllPicked           WebSocketEventType = "AllPicked"
	WebSocketEventTypeGameFinished        WebSocketEventType = "GameFinished"
	WebSocketEventTypeGameSettingsUpdated WebSocketEventType = "GameSettingsUpdated"
	WebSocketEventTypeGameStarted         WebSocketEventType = "GameStarted"
	WebSocketEventTypeHideQRCode          WebSocketEventType = "HideQRCode"
	WebSocketEventTypeInitialized         WebSocketEventType = "Initialized"
	WebSocketEventTypeMessageCreated      WebSocketEventType = "MessageCreated"
	WebSocketEventTypePickCanceled        WebSocketEventType = "PickCanceled"
	WebSocketEventTypePickFinished        WebSocketEventType = "PickFinished"
	WebSocketEventTypePickStarted         WebSocketEventType = "PickStarted"
	WebSocketEventTypeShowQRCode          WebSocketEventType = "ShowQRCode"
)

// Valid indicates whether the value is a known member of the WebSocketEventType enum.
func (e WebSocketEventType) Valid() bool {
	switch e {
	case WebSocketEventTypeAllPicked:
		return true
	case WebSocketEventTypeGameFinished:
		return true
	case WebSocketEventTypeGameSettingsUpdated:
		return true
	case WebSocketEventTypeGameStarted:
		return true
	case WebSocketEventTypeHideQRCode:
		return true
	case WebSocketEventTypeInitialized:
		return true
	case WebSocketEventTypeMessageCreated:
		return true
	case WebSocketEventTypePickCanceled:
		return true
	case WebSocketEventTypePickFinished:
		return true
	case WebSocketEventTypePickStarted:
		return true
	case WebSocketEventTypeShowQRCode:
		return true
	default:
		return false
	}
}

// Defines values for WebSocketMode.
const (
	Display     WebSocketMode = "display"
	Participant WebSocketMode = "participant"
)

// Valid indicates whether the value is a known member of the WebSocketMode enum.
func (e WebSocketMode) Valid() bool {
	switch e {
	case Display:
		return true
	case Participant:
		return true
	default:
		return false
	}
}

// AllPickedBody defines model for AllPickedBody.
type AllPickedBody struct {
	PickedBalls []PickedBall `json:"pickedBalls"`
}

// BingoSummary 現在ビンゴしている参加者の概要。
type BingoSummary struct {
	BingoOrders []int `json:"bingoOrders"`
	User        User  `json:"user"`
}

// BingoUpdate PickFinished の body で使う新規ビンゴ情報。カード詳細、ライン index、cell index は含めない。
type BingoUpdate struct {
	BingoOrders    []int `json:"bingoOrders"`
	NewBingoOrders []int `json:"newBingoOrders"`
	User           User  `json:"user"`
}

// Card participant にだけ送るカード snapshot。
type Card struct {
	BingoLines []Line `json:"bingoLines"`

	// CardID UUID string。
	CardID UUID       `json:"cardId"`
	Cells  []CardCell `json:"cells"`

	// OwnerUserID traP ID。
	OwnerUserID UserID `json:"ownerUserId"`
	ReachLines  []Line `json:"reachLines"`
}

// CardCell defines model for CardCell.
type CardCell struct {
	CellState   CardCellState `json:"cellState"`
	DisplayText string        `json:"displayText"`
	Index       int           `json:"index"`

	// Number 中央 FREE は null。
	Number *int `json:"number"`
}

// CardCellState defines model for CardCellState.
type CardCellState string

// CardChanges participant の PickFinished にだけ含める演出用差分。
type CardChanges struct {
	NewBingoLines     []Line `json:"newBingoLines"`
	NewReachLines     []Line `json:"newReachLines"`
	OpenedCellIndices []int  `json:"openedCellIndices"`
}

// CreateMessageRequest defines model for CreateMessageRequest.
type CreateMessageRequest struct {
	Content string `json:"content"`
}

// CreateRoomRequest defines model for CreateRoomRequest.
type CreateRoomRequest struct {
	// Settings 作成・更新時に渡すゲーム設定。adminUserIds は指定した場合だけ admin 一覧を置き換える。
	Settings GameSettingsInput `json:"settings"`
}

// DateTime ISO 8601 datetime string。
type DateTime = time.Time

// DisplayAllPickedEvent defines model for DisplayAllPickedEvent.
type DisplayAllPickedEvent struct {
	Body AllPickedBody             `json:"body"`
	Type DisplayAllPickedEventType `json:"type"`
}

// DisplayAllPickedEventType defines model for DisplayAllPickedEvent.Type.
type DisplayAllPickedEventType string

// DisplayGameFinishedBody defines model for DisplayGameFinishedBody.
type DisplayGameFinishedBody struct {
	BingoSummaries   []BingoSummary                   `json:"bingoSummaries"`
	ParticipantCount int                              `json:"participantCount"`
	PickState        DisplayGameFinishedBodyPickState `json:"pickState"`
	State            DisplayGameFinishedBodyState     `json:"state"`
}

// DisplayGameFinishedBodyPickState defines model for DisplayGameFinishedBody.PickState.
type DisplayGameFinishedBodyPickState string

// DisplayGameFinishedBodyState defines model for DisplayGameFinishedBody.State.
type DisplayGameFinishedBodyState string

// DisplayGameFinishedEvent defines model for DisplayGameFinishedEvent.
type DisplayGameFinishedEvent struct {
	Body DisplayGameFinishedBody      `json:"body"`
	Type DisplayGameFinishedEventType `json:"type"`
}

// DisplayGameFinishedEventType defines model for DisplayGameFinishedEvent.Type.
type DisplayGameFinishedEventType string

// DisplayGameSettingsUpdatedBody defines model for DisplayGameSettingsUpdatedBody.
type DisplayGameSettingsUpdatedBody struct {
	Settings GameSettings `json:"settings"`
}

// DisplayGameSettingsUpdatedEvent defines model for DisplayGameSettingsUpdatedEvent.
type DisplayGameSettingsUpdatedEvent struct {
	Body DisplayGameSettingsUpdatedBody      `json:"body"`
	Type DisplayGameSettingsUpdatedEventType `json:"type"`
}

// DisplayGameSettingsUpdatedEventType defines model for DisplayGameSettingsUpdatedEvent.Type.
type DisplayGameSettingsUpdatedEventType string

// DisplayGameStartedBody defines model for DisplayGameStartedBody.
type DisplayGameStartedBody struct {
	ParticipantCount int `json:"participantCount"`
}

// DisplayGameStartedEvent defines model for DisplayGameStartedEvent.
type DisplayGameStartedEvent struct {
	Body DisplayGameStartedBody      `json:"body"`
	Type DisplayGameStartedEventType `json:"type"`
}

// DisplayGameStartedEventType defines model for DisplayGameStartedEvent.Type.
type DisplayGameStartedEventType string

// DisplayHideQRCodeEvent defines model for DisplayHideQRCodeEvent.
type DisplayHideQRCodeEvent struct {
	Body HideQRCodeBody             `json:"body"`
	Type DisplayHideQRCodeEventType `json:"type"`
}

// DisplayHideQRCodeEventType defines model for DisplayHideQRCodeEvent.Type.
type DisplayHideQRCodeEventType string

// DisplayInitializedBody defines model for DisplayInitializedBody.
type DisplayInitializedBody struct {
	BingoSummaries   []BingoSummary `json:"bingoSummaries"`
	ParticipantCount int            `json:"participantCount"`
	PickState        PickState      `json:"pickState"`
	PickedBalls      []PickedBall   `json:"pickedBalls"`
	QrCodeVisible    bool           `json:"qrCodeVisible"`
	Settings         GameSettings   `json:"settings"`
	State            RoomState      `json:"state"`
}

// DisplayInitializedEvent defines model for DisplayInitializedEvent.
type DisplayInitializedEvent struct {
	Body DisplayInitializedBody      `json:"body"`
	Type DisplayInitializedEventType `json:"type"`
}

// DisplayInitializedEventType defines model for DisplayInitializedEvent.Type.
type DisplayInitializedEventType string

// DisplayMessageCreatedEvent defines model for DisplayMessageCreatedEvent.
type DisplayMessageCreatedEvent struct {
	Body MessageCreatedBody             `json:"body"`
	Type DisplayMessageCreatedEventType `json:"type"`
}

// DisplayMessageCreatedEventType defines model for DisplayMessageCreatedEvent.Type.
type DisplayMessageCreatedEventType string

// DisplayPickCanceledEvent defines model for DisplayPickCanceledEvent.
type DisplayPickCanceledEvent struct {
	Body PickCanceledBody             `json:"body"`
	Type DisplayPickCanceledEventType `json:"type"`
}

// DisplayPickCanceledEventType defines model for DisplayPickCanceledEvent.Type.
type DisplayPickCanceledEventType string

// DisplayPickFinishedBody defines model for DisplayPickFinishedBody.
type DisplayPickFinishedBody struct {
	BingoSummaries   []BingoSummary `json:"bingoSummaries"`
	NewBingos        []BingoUpdate  `json:"newBingos"`
	NewReaches       []ReachUpdate  `json:"newReaches"`
	ParticipantCount int            `json:"participantCount"`
	PickState        PickState      `json:"pickState"`
	PickedBall       PickedBall     `json:"pickedBall"`
	PickedBalls      []PickedBall   `json:"pickedBalls"`
}

// DisplayPickFinishedEvent defines model for DisplayPickFinishedEvent.
type DisplayPickFinishedEvent struct {
	Body DisplayPickFinishedBody      `json:"body"`
	Type DisplayPickFinishedEventType `json:"type"`
}

// DisplayPickFinishedEventType defines model for DisplayPickFinishedEvent.Type.
type DisplayPickFinishedEventType string

// DisplayPickStartedEvent defines model for DisplayPickStartedEvent.
type DisplayPickStartedEvent struct {
	Body PickStartedBody             `json:"body"`
	Type DisplayPickStartedEventType `json:"type"`
}

// DisplayPickStartedEventType defines model for DisplayPickStartedEvent.Type.
type DisplayPickStartedEventType string

// DisplayShowQRCodeEvent defines model for DisplayShowQRCodeEvent.
type DisplayShowQRCodeEvent struct {
	Body ShowQRCodeBody             `json:"body"`
	Type DisplayShowQRCodeEventType `json:"type"`
}

// DisplayShowQRCodeEventType defines model for DisplayShowQRCodeEvent.Type.
type DisplayShowQRCodeEventType string

// DisplayWebSocketEvent defines model for DisplayWebSocketEvent.
type DisplayWebSocketEvent = WebSocketEventBase

// EmptyObject defines model for EmptyObject.
type EmptyObject = map[string]interface{}

// Error defines model for Error.
type Error struct {
	Code        string `json:"code"`
	Description string `json:"description"`
	Message     string `json:"message"`
}

// GameSettings defines model for GameSettings.
type GameSettings struct {
	Admins      []User `json:"admins"`
	Description string `json:"description"`
	Name        string `json:"name"`
}

// GameSettingsInput 作成・更新時に渡すゲーム設定。adminUserIds は指定した場合だけ admin 一覧を置き換える。
type GameSettingsInput struct {
	AdminUserIds *[]UserID `json:"adminUserIds,omitempty"`
	Description  string    `json:"description"`
	Name         string    `json:"name"`
}

// HideQRCodeBody defines model for HideQRCodeBody.
type HideQRCodeBody = EmptyObject

// Line defines model for Line.
type Line = []int

// Message defines model for Message.
type Message struct {
	Author  User   `json:"author"`
	Content string `json:"content"`

	// CreatedAt ISO 8601 datetime string。
	CreatedAt DateTime `json:"createdAt"`

	// MessageID UUID string。
	MessageID UUID `json:"messageId"`
}

// MessageCreatedBody defines model for MessageCreatedBody.
type MessageCreatedBody struct {
	Message Message `json:"message"`
}

// ParticipantAllPickedEvent defines model for ParticipantAllPickedEvent.
type ParticipantAllPickedEvent struct {
	Body AllPickedBody                 `json:"body"`
	Type ParticipantAllPickedEventType `json:"type"`
}

// ParticipantAllPickedEventType defines model for ParticipantAllPickedEvent.Type.
type ParticipantAllPickedEventType string

// ParticipantGameFinishedBody defines model for ParticipantGameFinishedBody.
type ParticipantGameFinishedBody struct {
	BingoSummaries []BingoSummary `json:"bingoSummaries"`

	// Card participant にだけ送るカード snapshot。
	Card      Card                                 `json:"card"`
	PickState ParticipantGameFinishedBodyPickState `json:"pickState"`
	State     ParticipantGameFinishedBodyState     `json:"state"`
}

// ParticipantGameFinishedBodyPickState defines model for ParticipantGameFinishedBody.PickState.
type ParticipantGameFinishedBodyPickState string

// ParticipantGameFinishedBodyState defines model for ParticipantGameFinishedBody.State.
type ParticipantGameFinishedBodyState string

// ParticipantGameFinishedEvent defines model for ParticipantGameFinishedEvent.
type ParticipantGameFinishedEvent struct {
	Body ParticipantGameFinishedBody      `json:"body"`
	Type ParticipantGameFinishedEventType `json:"type"`
}

// ParticipantGameFinishedEventType defines model for ParticipantGameFinishedEvent.Type.
type ParticipantGameFinishedEventType string

// ParticipantGameSettingsUpdatedBody defines model for ParticipantGameSettingsUpdatedBody.
type ParticipantGameSettingsUpdatedBody struct {
	Settings GameSettings `json:"settings"`
}

// ParticipantGameSettingsUpdatedEvent defines model for ParticipantGameSettingsUpdatedEvent.
type ParticipantGameSettingsUpdatedEvent struct {
	Body ParticipantGameSettingsUpdatedBody      `json:"body"`
	Type ParticipantGameSettingsUpdatedEventType `json:"type"`
}

// ParticipantGameSettingsUpdatedEventType defines model for ParticipantGameSettingsUpdatedEvent.Type.
type ParticipantGameSettingsUpdatedEventType string

// ParticipantGameStartedBody defines model for ParticipantGameStartedBody.
type ParticipantGameStartedBody struct {
	// Card participant にだけ送るカード snapshot。
	Card Card `json:"card"`
}

// ParticipantGameStartedEvent defines model for ParticipantGameStartedEvent.
type ParticipantGameStartedEvent struct {
	Body ParticipantGameStartedBody      `json:"body"`
	Type ParticipantGameStartedEventType `json:"type"`
}

// ParticipantGameStartedEventType defines model for ParticipantGameStartedEvent.Type.
type ParticipantGameStartedEventType string

// ParticipantInitializedBody defines model for ParticipantInitializedBody.
type ParticipantInitializedBody struct {
	BingoSummaries []BingoSummary `json:"bingoSummaries"`

	// Card participant にだけ送るカード snapshot。
	Card        *Card        `json:"card,omitempty"`
	PickState   PickState    `json:"pickState"`
	PickedBalls []PickedBall `json:"pickedBalls"`
	Settings    GameSettings `json:"settings"`
	State       RoomState    `json:"state"`
}

// ParticipantInitializedEvent defines model for ParticipantInitializedEvent.
type ParticipantInitializedEvent struct {
	Body ParticipantInitializedBody      `json:"body"`
	Type ParticipantInitializedEventType `json:"type"`
}

// ParticipantInitializedEventType defines model for ParticipantInitializedEvent.Type.
type ParticipantInitializedEventType string

// ParticipantMessageCreatedEvent defines model for ParticipantMessageCreatedEvent.
type ParticipantMessageCreatedEvent struct {
	Body MessageCreatedBody                 `json:"body"`
	Type ParticipantMessageCreatedEventType `json:"type"`
}

// ParticipantMessageCreatedEventType defines model for ParticipantMessageCreatedEvent.Type.
type ParticipantMessageCreatedEventType string

// ParticipantPickCanceledEvent defines model for ParticipantPickCanceledEvent.
type ParticipantPickCanceledEvent struct {
	Body PickCanceledBody                 `json:"body"`
	Type ParticipantPickCanceledEventType `json:"type"`
}

// ParticipantPickCanceledEventType defines model for ParticipantPickCanceledEvent.Type.
type ParticipantPickCanceledEventType string

// ParticipantPickFinishedBody defines model for ParticipantPickFinishedBody.
type ParticipantPickFinishedBody struct {
	BingoSummaries []BingoSummary `json:"bingoSummaries"`

	// Card participant にだけ送るカード snapshot。
	Card Card `json:"card"`

	// CardChanges participant の PickFinished にだけ含める演出用差分。
	CardChanges CardChanges   `json:"cardChanges"`
	NewBingos   []BingoUpdate `json:"newBingos"`
	NewReaches  []ReachUpdate `json:"newReaches"`
	PickState   PickState     `json:"pickState"`
	PickedBall  PickedBall    `json:"pickedBall"`
	PickedBalls []PickedBall  `json:"pickedBalls"`
}

// ParticipantPickFinishedEvent defines model for ParticipantPickFinishedEvent.
type ParticipantPickFinishedEvent struct {
	Body ParticipantPickFinishedBody      `json:"body"`
	Type ParticipantPickFinishedEventType `json:"type"`
}

// ParticipantPickFinishedEventType defines model for ParticipantPickFinishedEvent.Type.
type ParticipantPickFinishedEventType string

// ParticipantPickStartedEvent defines model for ParticipantPickStartedEvent.
type ParticipantPickStartedEvent struct {
	Body PickStartedBody                 `json:"body"`
	Type ParticipantPickStartedEventType `json:"type"`
}

// ParticipantPickStartedEventType defines model for ParticipantPickStartedEvent.Type.
type ParticipantPickStartedEventType string

// ParticipantSummary 参加者一覧や display 向けの概要。admin 権限、カード詳細、リーチ情報、ビンゴ情報は含めない。
type ParticipantSummary struct {
	// JoinedAt ISO 8601 datetime string。
	JoinedAt DateTime `json:"joinedAt"`
	User     User     `json:"user"`
}

// ParticipantWebSocketEvent defines model for ParticipantWebSocketEvent.
type ParticipantWebSocketEvent = WebSocketEventBase

// PickCanceledBody defines model for PickCanceledBody.
type PickCanceledBody = EmptyObject

// PickStartedBody defines model for PickStartedBody.
type PickStartedBody = EmptyObject

// PickState defines model for PickState.
type PickState string

// PickedBall defines model for PickedBall.
type PickedBall struct {
	Number int `json:"number"`

	// PickedAt ISO 8601 datetime string。
	PickedAt DateTime `json:"pickedAt"`

	// PickedBallID UUID string。
	PickedBallID UUID `json:"pickedBallId"`
}

// ReachUpdate PickFinished の body で使う初リーチ情報。カード詳細、リーチライン index、cell index は含めない。
type ReachUpdate struct {
	User User `json:"user"`
}

// Room defines model for Room.
type Room struct {
	BingoSummaries []BingoSummary `json:"bingoSummaries"`

	// CreatedAt ISO 8601 datetime string。
	CreatedAt     DateTime             `json:"createdAt"`
	Participants  []ParticipantSummary `json:"participants"`
	PickState     PickState            `json:"pickState"`
	QrCodeVisible bool                 `json:"qrCodeVisible"`

	// RoomCode 6 桁の数字文字列。
	RoomCode RoomCode `json:"roomCode"`

	// RoomID ルーム ID。
	RoomID   RoomID       `json:"roomId"`
	Settings GameSettings `json:"settings"`
	State    RoomState    `json:"state"`

	// UpdatedAt ISO 8601 datetime string。
	UpdatedAt DateTime `json:"updatedAt"`
}

// RoomCode 6 桁の数字文字列。
type RoomCode = string

// RoomID UUID string。
type RoomID = UUID

// RoomState defines model for RoomState.
type RoomState string

// ShowQRCodeBody defines model for ShowQRCodeBody.
type ShowQRCodeBody = EmptyObject

// UUID UUID string。
type UUID = string

// UpdateGameSettingsRequest defines model for UpdateGameSettingsRequest.
type UpdateGameSettingsRequest struct {
	// Settings 作成・更新時に渡すゲーム設定。adminUserIds は指定した場合だけ admin 一覧を置き換える。
	Settings GameSettingsInput `json:"settings"`
}

// User defines model for User.
type User struct {
	Name string `json:"name"`

	// UserID traP ID。
	UserID UserID `json:"userId"`
}

// UserID traP ID。
type UserID = string

// WebSocketEventBase defines model for WebSocketEventBase.
type WebSocketEventBase struct {
	Body map[string]interface{} `json:"body"`
	Type WebSocketEventType     `json:"type"`
}

// WebSocketEventType defines model for WebSocketEventType.
type WebSocketEventType string

// WebSocketMode defines model for WebSocketMode.
type WebSocketMode string

// AdminRequired defines model for AdminRequired.
type AdminRequired = Error

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// RoomNotFound defines model for RoomNotFound.
type RoomNotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// forwardedUserContextKey is the context key for forwardedUser security scheme
type forwardedUserContextKey string

// ConnectRoomWebSocketParams defines parameters for ConnectRoomWebSocket.
type ConnectRoomWebSocketParams struct {
	// Mode participant, display のいずれか。card が必要な参加者は participant mode、card を受け取らない表示・運営画面は display mode で接続する。
	Mode WebSocketMode `form:"mode" json:"mode"`
}

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = CreateRoomRequest

// CreateMessageJSONRequestBody defines body for CreateMessage for application/json ContentType.
type CreateMessageJSONRequestBody = CreateMessageRequest

// UpdateGameSettingsJSONRequestBody defines body for UpdateGameSettings for application/json ContentType.
type UpdateGameSettingsJSONRequestBody = UpdateGameSettingsRequest
